### PR TITLE
Added numba support.

### PR DESCRIPTION
**Pull request by douglowe**
Both functions have been adapted to support precompiling
using numba - this I've done using brute-force (changing
*all* integer values to real) - but probably only 1 or 2 values
actually needed fixing like this.

Speed up is ~x10 (for repeat usage of the function). I've anything
more fancy than the standard jit module though, so possibly more
gains could be made later?

### CODE REVIEW

**Comment by fmalina** [comment]
Thank you for this, if you could only change the values that actually need to and amend your PR, I'll accept

**Comment by pedromorgan** [comment]
It's a HUGE new dependency though, that's my reservation..

**Review by fmalina — CHANGES_REQUESTED** [review]
Please only change integer values where absolutely necessary

**Comment by fmalina** [comment]
That can be handled by try and except ImportError with a dummy jit decorator func. I am happy to do that work making numba optional if only the necessary integers are converted @douglowe 10 times speed improvement is great

**Comment by douglowe** [comment]
Apologies for the delay in replying. I've gone back through the code to test the changes made, and found the 4 numbers which needed changing, which are all in the bng_to_latlon.py file. I can't remember why I made similar changes in the latlon_to_bng.py code - if it was because there was a similar issue at the time, or if I was just being consistent with the other changes I'd made - whichever it was, changes aren't needed in that file, so I've removed them all.

**Comment by fmalina** [comment]
This is now released on pypi, phew

**Pull request merged**
